const nodeGlobals = {
  console: "readonly",
  process: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  require: "readonly",
  module: "readonly",
  exports: "readonly",
  Buffer: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  URL: "readonly",
  fetch: "readonly",
};

const browserGlobals = {
  window: "readonly",
  document: "readonly",
  navigator: "readonly",
  performance: "readonly",
  PerformanceObserver: "readonly",
  console: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  URL: "readonly",
  fetch: "readonly",
  Blob: "readonly",
  FormData: "readonly",
  XMLHttpRequest: "readonly",
  localStorage: "readonly",
  sessionStorage: "readonly",
  location: "readonly",
  history: "readonly",
  screen: "readonly",
  MutationObserver: "readonly",
  IntersectionObserver: "readonly",
  ResizeObserver: "readonly",
  requestAnimationFrame: "readonly",
  cancelAnimationFrame: "readonly",
  getComputedStyle: "readonly",
  matchMedia: "readonly",
  Node: "readonly",
  Element: "readonly",
  HTMLElement: "readonly",
  Image: "readonly",
  Event: "readonly",
  CustomEvent: "readonly",
  AbortController: "readonly",
  Promise: "readonly",
  Map: "readonly",
  Set: "readonly",
  WeakMap: "readonly",
  Symbol: "readonly",
  JSON: "readonly",
  Math: "readonly",
  Date: "readonly",
  Array: "readonly",
  Object: "readonly",
  String: "readonly",
  Number: "readonly",
  Boolean: "readonly",
  RegExp: "readonly",
  Error: "readonly",
  parseInt: "readonly",
  parseFloat: "readonly",
  isNaN: "readonly",
  isFinite: "readonly",
  decodeURIComponent: "readonly",
  encodeURIComponent: "readonly",
  caches: "readonly",
  CSSRule: "readonly",
  CSSStyleDeclaration: "readonly",
  NodeFilter: "readonly",
  EventTarget: "readonly",
  DOMTokenList: "readonly",
};

export default [
  {
    ignores: ["node_modules/**", ".next/**", "dist/**", ".claude/**", "skills/**"],
  },
  {
    files: ["scripts/**/*.js"],
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
    },
    languageOptions: {
      globals: nodeGlobals,
    },
  },
  {
    files: ["components/**/*.js", "pages/**/*.js"],
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
    },
    languageOptions: {
      globals: { ...browserGlobals, ...nodeGlobals, React: "readonly" },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
  },
  {
    files: ["snippets/**/*.js"],
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-console": "off",
    },
    languageOptions: {
      globals: browserGlobals,
    },
  },
];
